/**
 * Supabase Database Types
 * 
 * This file is auto-generated by running: pnpm db:types
 * Do not edit manually - changes will be overwritten.
 * 
 * Run `supabase gen types typescript --local > src/types/supabase.ts`
 * to regenerate after schema changes.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string | null;
          full_name: string | null;
          role: "beneficiario" | "consultor" | "tecnico" | "admin" | "asociado";
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id: string;
          email?: string | null;
          full_name?: string | null;
          role?: "beneficiario" | "consultor" | "tecnico" | "admin" | "asociado";
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string | null;
          full_name?: string | null;
          role?: "beneficiario" | "consultor" | "tecnico" | "admin" | "asociado";
          created_at?: string;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      // Placeholder: Run `pnpm db:types` to generate full types from your Supabase schema
      [key: string]: {
        Row: Record<string, unknown>;
        Insert: Record<string, unknown>;
        Update: Record<string, unknown>;
        Relationships: unknown[];
      };
    };
    Views: {
      [key: string]: {
        Row: Record<string, unknown>;
        Relationships: unknown[];
      };
    };
    Functions: {
      [key: string]: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
    };
    Enums: {
      [key: string]: string;
    };
    CompositeTypes: {
      [key: string]: unknown;
    };
  };
};

// Helper types for easier access
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];

// Profile role type extracted from database
export type ProfileRole = Database["public"]["Tables"]["profiles"]["Row"]["role"];
